[tool.poetry]
name = "verbiverse"
version = "0.1.0"
description = ""
authors = ["Layton <caolei6767@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.13, >=3.9"
pyside6 = "^6.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
